name: Variables_workflow

env:
  cloud: aws

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      greeting: hello

    steps:
      - name: print_variables
        run: |
          echo $greeting $first_name $cloud

        env:
          first_name: madhu
